### ISSUE TITLE
Failed to find Game area

### ISSUE THREAD

**Issue by Luke987100** [D1firehail/AdeptiScanner-GI#5] opened 2022-06-19 09:50 UTC
i have been having a problem every time i attempt to capture it always gives this error and i don't know what to do?
i set the screen to 1600x900 i make sure that genshin is not overlapped by another app it still gives the same error please help

**Comment by D1firehail** [comment] 2022-06-19 10:00
I'll need to look at some screenshots to identify and give instructions on this, so I'll get back to you on Discord. 

Will post the cause on here before closing the issue

**Comment by D1firehail** [comment] 2022-06-19 10:46
Caused by combination of non-white window header (as mentioned in the readme) and non-standard button theme for the header.

**Closed by D1firehail** 2022-06-19 10:46 UTC

**Comment by Makein** [comment] 2022-09-28 21:36
I got same error right now

**Comment by D1firehail** [comment] 2022-09-28 21:41
Need more details to be able to indentify a cause. See [here](https://github.com/D1firehail/AdeptiScanner-GI#how-to-contact) for how to find me on discord and shoot me a DM. If that's not an option, let me know and I can provide instructions on how to get the necessary information in here instead
