### ISSUE TITLE
Feature Requests.

### ISSUE THREAD

**Issue by DChangka** [D1firehail/AdeptiScanner-GI#14] opened 2023-02-25 21:48 UTC
Hey!

I've been using your artifact scanning tool and am absolutely in love with it. It is a great replacement to the Amenoma tool (for which update operations have been kinda discontinued since 3.0).

Coming back to the topic at hand, I would like to put forth the following two feature requests that I feel would improve the convenience of this tool even further!

- Ability to continue scanning despite detecting a "duplicate artifact".

Many times while scanning through my artifact inventory, I would encounter a duplicate artifact (according to the scanner atleast. Although I do feel like it throws up that message even when there are no real duplicates.) that would immediately stop the scanning process.

My feature request here suggests the addition of an option that we can enable to allow the artifact scanner to continue scanning artifacts even if it does detect a duplicate. This, I feel will improve user convenience especially in situations where the artifact scan stops multiple times during an inventory scan due to detecting multiple duplicates along the way.

- Start artifact scan from the artifact that is selected by your in-game cursor.

According to the current behavior of the application, the artifact scan alwats starts from the top of the visible page irrespective of where your in-game cursor is positioned.
We can either make it an option or the new behavior of the application to start an artifact scan from the artifact that is selected by your in-game cursor.

And that's all I have to say here. I do hope that these feature requests get considered.

**Comment by D1firehail** [comment] 2023-02-25 23:39
There are 4 reasons why it would detect a duplicate (that I'm aware of):
- You reached the bottom of the page, so it's selecting artifacts you've already scanned in that run of Auto
- You have multiple artifacts which are identical (ignoring lock status). Very uncommon for 5-star and 4-star artifact, becomes a lot more common once you reach lower tier artifacts, but any unscanned artifacts at that point don't matter much
- The artifact grid it detected was off (usually due to the background), making it try clicking in a spot without an artifact
- Large amount of lag. If it sees a duplicate, it first tries waiting a bit longer and checking again. Lag would need to be longer than the re-check wait + initial click wait. If this is a common occurence, there's settings to adjust these wait times under `Advanced`

> Ability to continue scanning despite detecting a "duplicate artifact"

No, for the following reasons
- Would add unnecessary friction to the end of a normally working scan
- Would require manual intervention, at which case you might as well manually scroll to the next screen and click Auto again
- Detecting a duplicate before scanning all generally interesting artifacts should be very rare. 
   - If it happens consistently, you likely have 2 identical artifacts (with one or both being on the screen it ended on). If that's the case it's probably +0 artifacts and I'd suggest finding them and leveling one of them to +1
   - I've done all my testing with artifacts sorted by rarity (default). It may be slightly more common with other sorting options, but in that case I'd just add changing your sorting options to the instructions.

> Start artifact scan from the artifact that is selected by your in-game cursor
This *could* be done by registering the initially selected artifact and not actually scanning any artifacts until we find the duplicate of this one. However, I don't really see the practical use of this, since Auto always finished the screen it's on. 
If you can present a good reason for wanting to do it, I'll consider it.

**Closed** 2023-08-27 09:16 UTC
